import { OnboardingStep } from "@/lib/types";

export type RecommendationLanguage = "en" | "sv";

export const CITY_RECOMMENDATIONS = [
  "Stockholm",
  "Göteborg",
  "Malmö",
  "Uppsala",
  "Västerås",
  "Örebro",
  "Linköping",
  "Helsingborg",
  "Jönköping",
  "Norrköping",
  "Lund",
  "Umeå",
  "Gävle",
  "Borås",
  "Södertälje",
  "Karlstad",
  "Växjö",
  "Halmstad",
  "Sundsvall",
  "Luleå",
  "Eskilstuna",
  "Trollhättan",
  "Skövde",
  "Falun",
  "Kalmar",
  "Kristianstad",
];

export const CITY_RECOMMENDATIONS_EN = [...CITY_RECOMMENDATIONS];

export const ROLE_RECOMMENDATIONS = [
  "Cafébiträde",
  "Kassabiträde på café",
  "Butiksbiträde",
  "Säljhjälp i butik",
  "Varuplockare i butik",
  "Snabbmatsmedarbetare",
  "Serveringshjälp",
  "Diskhjälp",
  "Köksbiträde",
  "Glasskioskpersonal",
  "Biografvärd",
  "Festivalmedarbetare",
  "Incheckningshjälp på event",
  "Arenahjälp",
  "Cykelbudshjälp",
  "Paketsorterare",
  "Lagerplockare",
  "Receptionistassistent",
  "Kontorsassistent",
  "Sociala medier-assistent",
  "Innehållsassistent",
  "Foto/video-assistent",
  "Hundrastare",
  "Djurpassningshjälp",
  "Barnvakt",
  "Fritidsledarassistent",
  "Läxhjälpare",
  "Simhallsassistent",
  "Biblioteksassistent",
  "Städhjälp",
  "Frukostvärd på hotell",
  "Housekeeping-assistent",
  "Trädgårdshjälp",
  "Bilvårdsassistent",
  "Ungdomsagent på callcenter",
  "Hjälpledare i kodworkshop",
  "Junior webbassistent",
  "Speltest-assistent",
  "E-handelsassistent",
  "Kundservicepraktikant",
];

export const ROLE_RECOMMENDATIONS_EN = [
  "Cafe barista",
  "Cafe cashier",
  "Store assistant",
  "Retail sales helper",
  "Supermarket shelf stocker",
  "Fast-food team member",
  "Restaurant server helper",
  "Dishwashing assistant",
  "Kitchen prep assistant",
  "Ice cream kiosk staff",
  "Movie theater assistant",
  "Festival crew helper",
  "Event check-in assistant",
  "Sports arena helper",
  "Delivery bike helper",
  "Package sorting assistant",
  "Warehouse picker",
  "Reception helper",
  "Office admin helper",
  "Social media assistant",
  "Content creator assistant",
  "Photo/video helper",
  "Dog walker",
  "Pet sitting helper",
  "Babysitter",
  "After-school activity helper",
  "Homework support tutor",
  "Swim hall assistant",
  "Library helper",
  "Cleaner assistant",
  "Hotel breakfast helper",
  "Housekeeping helper",
  "Garden maintenance helper",
  "Car wash assistant",
  "Call center youth agent",
  "Coding workshop helper",
  "Junior web assistant",
  "Game testing helper",
  "E-commerce support assistant",
  "Customer support trainee",
];

export const INTEREST_RECOMMENDATIONS = [
  "Sport",
  "Fotboll",
  "Musik",
  "Gaming",
  "Träning",
  "Dans",
  "Film och serier",
  "Resor",
  "Mode",
  "Teknikprylar",
  "Skapande",
  "Friluftsliv",
  "Foto",
  "Läsning",
  "Sociala medier",
  "Bilar och motor",
  "Podcasts",
  "Språk",
  "Natur",
  "Basket",
  "Gym",
  "Konst",
  "Matlagning",
  "Bakning",
  "Volontärarbete",
];

export const INTEREST_RECOMMENDATIONS_EN = [
  "Sports",
  "Football",
  "Music",
  "Gaming",
  "Fitness",
  "Dance",
  "Movies and series",
  "Travel",
  "Fashion",
  "Tech gadgets",
  "Creative projects",
  "Outdoors",
  "Photography",
  "Reading",
  "Social media",
  "Cars and motors",
  "Podcasts",
  "Languages",
  "Nature",
  "Basketball",
  "Gym",
  "Art",
  "Cooking",
  "Baking",
  "Volunteering",
];

export const SKILL_RECOMMENDATIONS = [
  "Kundservice",
  "Kommunikation",
  "Samarbete",
  "Ansvarstagande",
  "Punktlighet",
  "Tidsplanering",
  "Problemlösning",
  "Positiv attityd",
  "Konflikthantering",
  "Säljstöd",
  "Kassahantering",
  "Livsmedelshygien",
  "Ordermottagning",
  "Publicering i sociala medier",
  "Bildredigering",
  "Videoredigering",
  "Excel grund",
  "Google Docs",
  "Canva",
  "Engelska i tal",
  "Svenska i tal",
  "Eventuppsättning",
  "Packning och sortering",
  "Grundläggande programmering",
  "HTML/CSS",
  "Barnpassning",
  "Läxhjälp",
  "Städrutiner",
];

export const SKILL_RECOMMENDATIONS_EN = [
  "Customer service",
  "Communication",
  "Teamwork",
  "Responsibility",
  "Punctuality",
  "Time management",
  "Problem solving",
  "Positive attitude",
  "Conflict handling",
  "Sales support",
  "Cash handling",
  "Food hygiene",
  "Order taking",
  "Social media posting",
  "Photo editing",
  "Video editing",
  "Excel basics",
  "Google Docs",
  "Canva",
  "English speaking",
  "Swedish speaking",
  "Event setup",
  "Packing and sorting",
  "Basic coding",
  "HTML/CSS",
  "Child supervision",
  "Tutoring basics",
  "Cleaning routines",
];

export const AVAILABILITY_RECOMMENDATIONS = [
  "Vardagar efter skolan",
  "Endast helger",
  "Kvällar (17:00-21:00)",
  "Fredagar och helger",
  "Heltid under sommaren",
  "Skollov",
  "Måndag/onsdag/fredag",
  "Valfri dag efter 16:00",
  "Flexibel deltid",
  "Varannan helg",
];

export const AVAILABILITY_RECOMMENDATIONS_EN = [
  "Weekdays after school",
  "Weekends only",
  "Evenings (17:00-21:00)",
  "Fridays and weekends",
  "Summer full-time",
  "School holidays",
  "Monday/Wednesday/Friday",
  "Any day after 16:00",
  "Flexible part-time",
  "Every other weekend",
];

export const EXPERIENCE_RECOMMENDATIONS = [
  "Hjälpte till vid skolevenemang med incheckning",
  "Var volontär på ungdomsidrott",
  "Hjälpte till på familjens café under helger",
  "Gav läxhjälp till yngre elever i matte/engelska",
  "Skötte sociala medier för skolklubb",
  "Arbetade i teamprojekt med deadlines",
  "Hjälpte grannar med djurpassning",
  "Organiserade klassens insamlingsevent",
  "Hjälpte till i lokalt aktivitetscenter",
  "Stöttade lokal butik med varupåfyllning",
  "Drev ett litet onlineprojekt för vidareförsäljning",
  "Skapade innehåll för skolaktiviteter",
  "Hjälpte till i fritidsverksamhet",
  "Assisterade i sommarlägeraktiviteter",
  "Arbetade deltid inom servering",
];

export const EXPERIENCE_RECOMMENDATIONS_EN = [
  "Helped at school events with visitor check-in",
  "Volunteered at youth sports activities",
  "Supported family cafe on busy weekends",
  "Tutored younger students in math/English",
  "Handled social media for school club",
  "Worked in team project with deadlines",
  "Helped neighbors with pet sitting",
  "Organized class fundraiser events",
  "Assisted in local community center",
  "Supported a local shop with restocking",
  "Managed small online reselling project",
  "Created content for school activities",
  "Helped in after-school programs",
  "Assisted in summer camp activities",
  "Worked part-time in food service",
];

export function recommendationSet(language: RecommendationLanguage) {
  if (language === "en") {
    return {
      cities: CITY_RECOMMENDATIONS_EN,
      roles: ROLE_RECOMMENDATIONS_EN,
      interests: INTEREST_RECOMMENDATIONS_EN,
      skills: SKILL_RECOMMENDATIONS_EN,
      availability: AVAILABILITY_RECOMMENDATIONS_EN,
      experience: EXPERIENCE_RECOMMENDATIONS_EN,
    };
  }
  return {
    cities: CITY_RECOMMENDATIONS,
    roles: ROLE_RECOMMENDATIONS,
    interests: INTEREST_RECOMMENDATIONS,
    skills: SKILL_RECOMMENDATIONS,
    availability: AVAILABILITY_RECOMMENDATIONS,
    experience: EXPERIENCE_RECOMMENDATIONS,
  };
}

export const ALL_CITY_RECOMMENDATIONS = Array.from(
  new Set([...CITY_RECOMMENDATIONS, ...CITY_RECOMMENDATIONS_EN]),
);

export const ALL_ROLE_RECOMMENDATIONS = Array.from(
  new Set([...ROLE_RECOMMENDATIONS, ...ROLE_RECOMMENDATIONS_EN]),
);

export function recommendationsForStep(
  step: OnboardingStep,
  language: RecommendationLanguage = "sv",
): string[] {
  const set = recommendationSet(language);
  if (step === "city") return set.cities;
  if (step === "targetRole") return set.roles;
  if (step === "interests") return set.interests;
  if (step === "skills") return set.skills;
  if (step === "availability") return set.availability;
  if (step === "experience") return set.experience;
  return [];
}

