import { OnboardingStep } from "@/lib/types";

export const CITY_RECOMMENDATIONS = [
  "Stockholm",
  "Gothenburg",
  "Malmo",
  "Uppsala",
  "Vasteras",
  "Orebro",
  "Linkoping",
  "Helsingborg",
  "Jonkoping",
  "Norrkoping",
  "Lund",
  "Umea",
  "Gavle",
  "Boras",
  "Sodertalje",
  "Karlstad",
  "Vaxjo",
  "Halmstad",
  "Sundsvall",
  "Lulea",
  "Eskilstuna",
  "Trollhattan",
  "Skovde",
  "Falun",
  "Kalmar",
  "Kristianstad",
];

export const ROLE_RECOMMENDATIONS = [
  "Cafe barista",
  "Cafe cashier",
  "Store assistant",
  "Retail sales helper",
  "Supermarket shelf stocker",
  "Fast-food team member",
  "Restaurant server helper",
  "Dishwashing assistant",
  "Kitchen prep assistant",
  "Ice cream kiosk staff",
  "Movie theater assistant",
  "Festival crew helper",
  "Event check-in assistant",
  "Sports arena helper",
  "Delivery bike helper",
  "Package sorting assistant",
  "Warehouse picker",
  "Reception helper",
  "Office admin helper",
  "Social media assistant",
  "Content creator assistant",
  "Photo/video helper",
  "Dog walker",
  "Pet sitting helper",
  "Babysitter",
  "After-school activity helper",
  "Homework support tutor",
  "Swim hall assistant",
  "Library helper",
  "Cleaner assistant",
  "Hotel breakfast helper",
  "Housekeeping helper",
  "Garden maintenance helper",
  "Car wash assistant",
  "Call center youth agent",
  "Coding workshop helper",
  "Junior web assistant",
  "Game testing helper",
  "E-commerce support assistant",
  "Customer support trainee",
];

export const INTEREST_RECOMMENDATIONS = [
  "Retail",
  "Coffee and cafes",
  "Food service",
  "Events",
  "Sports",
  "Childcare",
  "E-commerce",
  "Technology",
  "Social media",
  "Photography",
  "Design",
  "Music",
  "Gaming",
  "Animals",
  "Outdoors",
  "Logistics",
  "Hospitality",
  "Education",
  "Health and wellness",
  "Local community",
];

export const SKILL_RECOMMENDATIONS = [
  "Customer service",
  "Communication",
  "Teamwork",
  "Responsibility",
  "Punctuality",
  "Time management",
  "Problem solving",
  "Positive attitude",
  "Conflict handling",
  "Sales support",
  "Cash handling",
  "Food hygiene",
  "Order taking",
  "Social media posting",
  "Photo editing",
  "Video editing",
  "Excel basics",
  "Google Docs",
  "Canva",
  "English speaking",
  "Swedish speaking",
  "Event setup",
  "Packing and sorting",
  "Basic coding",
  "HTML/CSS",
  "Child supervision",
  "Tutoring basics",
  "Cleaning routines",
];

export const AVAILABILITY_RECOMMENDATIONS = [
  "Weekdays after school",
  "Weekends only",
  "Evenings (17:00-21:00)",
  "Fridays and weekends",
  "Summer full-time",
  "School holidays",
  "Monday/Wednesday/Friday",
  "Any day after 16:00",
  "Flexible part-time",
  "Every other weekend",
];

export const EXPERIENCE_RECOMMENDATIONS = [
  "Helped at school events with visitor check-in",
  "Volunteered at youth sports activities",
  "Supported family cafe on busy weekends",
  "Tutored younger students in math/English",
  "Handled social media for school club",
  "Worked in team project with deadlines",
  "Helped neighbors with pet sitting",
  "Organized class fundraiser events",
  "Assisted in local community center",
  "Supported a local shop with restocking",
  "Managed small online reselling project",
  "Created content for school activities",
  "Helped in after-school programs",
  "Assisted in summer camp activities",
  "Worked part-time in food service",
];

export function recommendationsForStep(step: OnboardingStep): string[] {
  if (step === "city") return CITY_RECOMMENDATIONS;
  if (step === "targetRole") return ROLE_RECOMMENDATIONS;
  if (step === "interests") return INTEREST_RECOMMENDATIONS;
  if (step === "skills") return SKILL_RECOMMENDATIONS;
  if (step === "availability") return AVAILABILITY_RECOMMENDATIONS;
  if (step === "experience") return EXPERIENCE_RECOMMENDATIONS;
  return [];
}
