"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { getJobById } from "@/lib/jobs";
import { useSession } from "@/hooks/use-session";
import { useCvCompletion } from "@/hooks/use-cv-completion";
import { getSupabaseClient } from "@/lib/supabase";
import { saveApplicationDraft, setJobSaved } from "@/lib/youth-job-flow";
import { swipeJob } from "@/lib/matching";
import type { JobPost } from "@/lib/types";
const listItems = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);
function ageRequirement(job: JobPost) { if (job.min_age == null && job.max_age == null) return null; if (job.min_age != null && job.max_age != null) return `${job.min_age}–${job.max_age} år`; return job.min_age != null ? `Minst ${job.min_age} år` : `Högst ${job.max_age} år`; }
export default function JobDetailPage() {
  const params = useParams<{ jobId: string }>(); const { user, profile } = useSession(); const { cvCompleted } = useCvCompletion(user?.id, profile?.role === "youth");
  const [job, setJob] = useState<JobPost | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(""), [alreadyApplied, setAlreadyApplied] = useState(false), [saved, setSaved] = useState(false), [showCvPrompt, setShowCvPrompt] = useState(false), [actionError, setActionError] = useState("");
  useEffect(() => { let active = true; void getJobById(params.jobId).then((result) => { if (active) setJob(result); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Kunde inte hämta annonsen."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [params.jobId]);
  useEffect(() => { if (!user || profile?.role !== "youth") return; let active = true; void Promise.all([getSupabaseClient().from("swipe_actions").select("decision").eq("youth_user_id", user.id).eq("job_id", params.jobId).eq("decision", "interested").maybeSingle(), getSupabaseClient().from("youth_saved_jobs").select("id").eq("youth_user_id", user.id).eq("job_id", params.jobId).maybeSingle()]).then(([application, bookmark]) => { if (active) { setAlreadyApplied(Boolean(application.data)); setSaved(Boolean(bookmark.data)); } }); return () => { active = false; }; }, [params.jobId, profile?.role, user]);
  if (loading) return <main className="mobile-shell"><p>Laddar annonsen...</p></main>; if (error || !job) return <main className="mobile-shell"><div className="card" style={{ padding: "1.25rem" }}><p>{error || "Annonsen hittades inte."}</p><Link href="/swipe">← Tillbaka till jobben</Link></div></main>;
  const requirements = [ageRequirement(job), ...listItems(job.requirements)].filter(Boolean); const benefits = listItems(job.benefits); const address = [job.address, job.postal_code, job.city].filter(Boolean).join(", ");
  const toggleSaved = async () => { try { await setJobSaved(job.id, !saved); setSaved(!saved); } catch (reason) { setActionError(reason instanceof Error ? reason.message : "Kunde inte spara jobbet."); } };
  const startApplication = async () => { try { if (cvCompleted) { await swipeJob(job.id, "interested"); setAlreadyApplied(true); } else { await saveApplicationDraft(job.id); setShowCvPrompt(true); } } catch (reason) { setActionError(reason instanceof Error ? reason.message : "Kunde inte påbörja ansökan."); } };
  return <main className="job-detail-page"><Link href="/swipe" className="job-detail-back">← Alla jobb</Link><article className="job-detail-card"><header className="job-detail-header"><div className="job-detail-heading"><p className="job-detail-company">{job.company_name || "Företag"}</p><h1>{job.title}</h1><p>{job.city} · {job.employment_type}</p></div></header><div className="job-detail-layout"><section className="job-detail-main"><section><h2>Om jobbet</h2><p>{job.description || "Ingen beskrivning angiven."}</p></section><section><h2>Tider</h2><p>{job.employment_type || job.category || "Tider enligt överenskommelse"}</p></section></section><aside className="job-detail-aside">{requirements.length > 0 && <section className="job-detail-panel"><h2>Krav</h2><ul>{requirements.map((item) => <li key={item}>{item}</li>)}</ul></section>}{benefits.length > 0 && <section className="job-detail-panel"><h2>Förmåner</h2><ul>{benefits.map((item) => <li key={item}>{item}</li>)}</ul></section>}<section className="job-detail-panel"><h2>Lön</h2><p>{job.salary_per_hour || "Lön enligt överenskommelse"}</p></section><section className="job-detail-panel"><h2>Adress</h2><p>{address || "Adress meddelas av arbetsgivaren"}</p></section>{profile?.role === "youth" && <><button type="button" className="secondary-btn" style={{ width: "100%", marginBottom: ".6rem" }} onClick={() => void toggleSaved()}>{saved ? "Ta bort sparat" : "Spara jobb"}</button>{alreadyApplied ? <p className="job-detail-applied">Din ansökan är skickad.</p> : <button type="button" className="cta-btn job-detail-apply" onClick={() => void startApplication()}>{cvCompleted ? "Skicka ansökan" : "Påbörja ansökan"}</button>}{actionError && <p style={{ color: "#b42318" }}>{actionError}</p>}</>}</aside></div></article>{showCvPrompt && <div role="dialog" aria-modal="true" style={{ position: "fixed", inset: 0, zIndex: 10, display: "grid", placeItems: "center", padding: "1.25rem", background: "rgba(0,0,0,.45)" }}><section className="card" style={{ maxWidth: 380, padding: "1.4rem" }}><h2>Du är nästan där</h2><p>För att skicka din ansökan behöver företaget kunna se ett CV.</p><Link className="cta-btn" style={{ display: "block", textAlign: "center" }} href={`/youth/cv?job=${encodeURIComponent(job.id)}&title=${encodeURIComponent(job.title)}`}>Skapa ditt CV</Link><button type="button" className="secondary-btn" style={{ width: "100%", marginTop: ".7rem" }} onClick={() => setShowCvPrompt(false)}>Tillbaka till jobbet</button></section></div>}</main>;
}
